name: CI

on:
  push:
    branches: [master]
  pull_request:
    # Include ready_for_review to trigger CI when draft PR is marked ready
    types: [opened, synchronize, reopened, ready_for_review]

env:
  RUST_BACKTRACE: short
  RUSTFLAGS: -D warnings
  CARGO_TERM_COLOR: always
  LEXE_RUST_FMT_VERSION: nightly-2025-10-16

jobs:
  clippy:
    if: github.event_name == 'push' || github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: Swatinem/rust-cache@v2
      - run: cargo clippy --manifest-path rust-example/Cargo.toml --all-targets -- -D warnings

  fmt:
    if: github.event_name == 'push' || github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: rustup install ${{ env.LEXE_RUST_FMT_VERSION }} --profile minimal --component rustfmt
      - run: rustup run ${{ env.LEXE_RUST_FMT_VERSION }} cargo fmt --manifest-path rust-example/Cargo.toml -- --check
